---
- hosts: do
  remote_user: root

  tasks:
    - name: add docker repo
      shell:  yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: install docker-ce
      yum:
        name: 'docker-ce'
        state: latest
    - name: start docker
      shell: systemctl start docker
    - name: enable autostart docker
      shell: systemctl enable docker
    - name: check docker hello-world
      shell: docker run hello-world
