version: '3'
services:
  db:
    image: "postgres:9.6.5"
    container_name: "postgres"

    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - env_file
    networks:
      - db_nw
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD="*****"
      - "POSTGRES_USER=postgres"
networks:
  db_nw:
    driver: bridge
volumes:
  dbdata:
